### ISSUE TITLE
import data from ant

### ISSUE THREAD

**Issue by dhetting** [USEPA/EPA_MOVES_Model#1]
How do you import data for a batch run using MOVES 3.0? In MOVES2014, I could run `java -Xmx512M 'gov.epa.otaq.moves.master.commandline.MOVESCommandLine -i {import_file}`, but that errors now. Is there another way to do that now?

**Comment by anna965** [comment]
I have a similar problem. There is a significant number of input databases to generate during MOVES run.  It is important to automate data import process in the interest of quality and time saving.  In MOVES2014b we used the following command line statement for batch run: java -Xmx512M ‘gov.epa.otaq.moves.master.commandline.MOVESCommandLine -i XML. Please point to the corresponding MOVES3 ant command for executing import run specification on command line.

**Comment by anna965** [comment]
I have a similar problem. There is a significant number of input databases to generate during MOVES run.  It is important to automate data import process in the interest of quality and time saving.  In MOVES2014b we used the following command line statement for batch run: java -Xmx512M ‘gov.epa.otaq.moves.master.commandline.MOVESCommandLine -i XML. Please point to the corresponding MOVES3 ant command for executing import run specification on command line.

**Comment by danielbizercox** [comment]
Thank you for submitting this issue. We have fixed it by including this command in Ant.

Users who want to use this feature before we release version 3.0.1 can download [build.xml](https://github.com/USEPA/EPA_MOVES_Model/raw/dev/v3.0.1/build.xml) to the root MOVES installation directory (overwriting the existing file). The model does not need to be recompiled to use this fix.

For help on how to use the new ant command, see the [Batch Mode Input Database Creation](https://github.com/USEPA/EPA_MOVES_Model/blob/dev/v3.0.1/docs/CommandLineMOVES.md#batch-mode-input-database-creation) documentation.

**Comment by danielbizercox** [comment]
Reopening until we release MOVES3.0.1.

**Comment by danielbizercox** [comment]
Reopening until we release MOVES3.0.1
