### ISSUE TITLE
XML cannot import sourcetypeyearvmt and related issues

### ISSUE THREAD

**Issue by JiaoyanHuang** [USEPA/EPA_MOVES_Model#11]
1. sourcetypeyearvmt cannot be added into Maria DB
I used CDM tool to create a XML file; however, 

```
<sourcetypeyearvmt>
	<filename>P:\ProjectData\921011 ICCT MOVES Support\MOVES_Input_Data\MOVE_NEI2017_data\sourcetypeyearvmt\c34001_NEI2017_sourcetypeyearvmt.tab</filename>
```

VMT cannot be added to Maria DB, others inputs work fine.

2. When I submit a county scale run via GUI, without VMT the model cannot be run. However, followed by previous XML VMT issue, even the VMT is empty in CDB, I can still run county scale MOVES, using following command

```
call ant run -Drunspec="P:/ProjectData/921011 ICCT MOVES Support/ICCT_NJ/RunSpecs/XXXX.mrs"
```

**Comment by danielbizercox** [comment]
Thank you for reporting this issue. We have confirmed that the only VMT configuration that works with the XML importers is using the HPMSvTypeYear table. This issue will be resolved in MOVES3.0.1.

Please note that when MOVES is run on the command line using the "ant run" command, not all of the County DB/Project DB data quality checks are performed. So while the model still runs with this missing data, the output from these runs will not be valid. We recommend ensuring that the GUI gives you all green checks before starting runs if you are running from the command line.
