### ISSUE TITLE
dbimporter command specified within the CommandLineMOVES docs does not exist in MOVES3.0.0

### ISSUE THREAD

**Issue by olly123456** [USEPA/EPA_MOVES_Model#22]
When running the following code from within the MOVES directory "C:\Users\Public\EPA\MOVES\MOVES3.0", as suggested [here](https://github.com/USEPA/EPA_MOVES_Model/blob/master/docs/CommandLineMOVES.md) 
`ant dbimporter -Dimport="c:\mydbimporter.xml"`
The following error is displayed:
`Target "dbimporter" does not exist in the project "MOVES".`
Are [these](https://github.com/USEPA/EPA_MOVES_Model/blob/master/docs/CommandLineMOVES.md) instructions relevant for MOVES3.0.0?

**Comment by danielbizercox** [comment]
No, those instructions pre-date MOVES3.0.0. You'll need to either download and install MOVES3.0.1, or follow the instructions on #1 to patch this feature in 3.0.0.
