### ISSUE TITLE
Missing methane (CH4) for MY2010+ LD diesel

### ISSUE THREAD

**Issue by mbeardsl** [USEPA/EPA_MOVES_Model#36]
In MOVES3, methane for light-duty diesel  (reg class 20 & 30) is set to zero for model years 2010 and later.  It should be 38% of the total hydrocarbons from these vehicles.  While LD diesel are a small fraction of the U.S. fleet and modern diesels emit very little hydrocarbon, the error create slight underestimates of fleet-wide methane and slight overestimates of fleet-wide VOC. 

Methane fractions for diesel vehicles are explained in Speciation of Total Organic Gas and Particulate Matter Emissions from Onroad Vehicles in MOVES3 (https://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=P1010THD.pdf) and recorded in the table methaneTHCratio.  There is very little data, so the methane fractions for LD diesel were taken from the methane measurements for heavy-duty (also sparse).  Methane for all 1960-2007 MY diesels is intended to be zero, and implemented correctly in MOVES3.   For MY 2007-2009, it is non-zero and implemented correctly.  But for MY 2010+, methane is intended to be 38% of the total hydrocarbons.  This was implemented correctly for the heavier diesel vehicles, but not for regulatory class 20 (cars) and 30 (light trucks).

**Comment by danielbizercox** [comment]
This will be fixed in MOVES3.0.3 via a database update. Users interested in implementing this fix before MOVES3.0.3 is released can follow the steps below:

1. Make a copy of the MOVES default database (for MOVES3.0.2, this is movesdb20210726) and name it movesdb20210726_fixissue36.
2. Using the new database, run the following SQL command (e.g, using HeidiSQL or MySQL Workbench):
```sql
REPLACE INTO methanethcratio (processID, fuelSubtypeID, regClassID, beginModelYearID, endModelYearID, CH4THCRatio, dataSourceID) VALUES (1,20,20,2010,2060,0.38,9012),(1,20,30,2010,2060,0.38,9012),(1,21,20,2010,2060,0.38,9012),(1,21,30,2010,2060,0.38,9012),(1,22,20,2010,2060,0.38,9012),(1,22,30,2010,2060,0.38,9012),(2,20,20,2010,2060,0.38,9012),(2,20,30,2010,2060,0.38,9012),(2,21,20,2010,2060,0.38,9012),(2,21,30,2010,2060,0.38,9012),(2,22,20,2010,2060,0.38,9012),(2,22,30,2010,2060,0.38,9012),(15,20,20,2010,2060,0.38,9012),(15,20,30,2010,2060,0.38,9012),(15,21,20,2010,2060,0.38,9012),(15,21,30,2010,2060,0.38,9012),(15,22,20,2010,2060,0.38,9012),(15,22,30,2010,2060,0.38,9012),(16,20,20,2010,2060,0.38,9012),(16,20,30,2010,2060,0.38,9012),(16,21,20,2010,2060,0.38,9012),(16,21,30,2010,2060,0.38,9012),(16,22,20,2010,2060,0.38,9012),(16,22,30,2010,2060,0.38,9012);
ANALYZE TABLE methanethcratio;
OPTIMIZE TABLE methanethcratio;
```
3. Configure MOVES to use your new database by updating the defaultDatabaseName entry in MOVESConfiguration.txt and maketodo.txt.
