### ISSUE TITLE
Proposal: remove feature for running onroad chemical mechanisms

### ISSUE THREAD

**Issue by EvanGrahamMurray** [USEPA/EPA_MOVES_Model#44]
The MOVES team is proposing to remove the feature for running chemical mechanisms as part of MOVES. 

Chemical mechanisms are used in MOVES to speciate organic gas emissions into species that are important for air quality modeling. Specifically, they map emissions from about 2 dozen integrated species (like methane and benzene) and the rest of the total organic gases (residual TOG, or NonHAPTOG) to lumped species (groups of real chemical species) that are important for modeling chemical reactions in the atmosphere. For more information on chemical mechanisms and speciation in general, please see the MOVES technical report, [Speciation of Total Organic Gas and Particulate Matter Emissions from Onroad Vehicles in MOVES3](https://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=P1010THD.pdf). 

For future air quality modeling, EPA plans to perform this speciation by post-processing MOVES output, for several reasons. This approach saves up to 50% of total computation time, allows us to model several different chemical mechanisms and to apply updated speciation profiles without needing to re-run MOVES, and makes MOVES easier to maintain and test. Therefore, we propose the following changes for the next posted version of the MOVES model:

1.	We add NonHAPTOG to the MOVES GUI, which is required for speciating TOG emissions outside of MOVES.
2.	We remove the four currently existing chemical mechanisms from the MOVES GUI.
3.	We stop testing and maintaining the chemical mechanisms in MOVES, in favor of doing this work via post-processing.

Please let us know if you have concerns about this proposed change to the MOVES methodology and the implications for your modeling procedures. We are especially looking for feedback from users who regularly use the chemical mechanisms in their modeling.

**Comment by danielbizercox** [comment]
This issue has been accepted for MOVES3.0.4, with additional functionality. 

First, we have extended this post-processing speciation approach to PM. Existing PM pollutants will remain available in the MOVES output, and PM emissions will be unchanged for backwards compatibility purposes. We have added two new PM pollutants for onroad emissions. The first, Total Organic Matter (TOM, pollutantID=123) is the sum of the existing Organic Carbon (OC) and Non-Carbon Organic Matter (NCOM) pollutants. The second, residual PM (pollutantID=124), is total PM aside from elemental carbon (EC), sulfate particulate (SO4), and TOM. The new pollutants allow PM organic and inorganic mass to be speciated separately. 

Second, we have made post-processing scripts available in the MOVES GUI to better support users who wish to use post-processing to speciate MOVES output. For onroad emissions, the script calculates the relative weight that each speciation profiles should be given for each SSC in MOVES output.  Profile weights are calculated for onroad residual TOG (NonHAPTOG), TOM, and residual PM. For nonroad emissions, the script maps the profiles to the NONHAPTOG and PM2.5 emissions with an implied weighting of one for each profile and source description.  Using the output of these scripts, modelers may apply chemical mechanisms to MOVES output and can change the mechanism which is applied without needing to rerun MOVES. These scripts are available in the "Tools" menu of the MOVES GUI, under "Onroad Speciation Profile Weighting Script", and "Nonroad Speciation Profile Script". We strongly recommend that modelers read all instructions and the help document before performing MOVES runs they wish to speciate.

We believe this new approach to speciation, with additional tooling to support modelers wishing to do air quality modeling, will make MOVES easier to use while maintaining functionality. This will also help MOVES better adapt to future frameworks for speciation and air quality modeling, including the release of new chemical mechanisms.
