### ISSUE TITLE
Accessing non-road inventory data and/or scrappage/survival curve

### ISSUE THREAD

**Issue by AnAbominableSnowman** [USEPA/EPA_MOVES_Model#57]
Hello,

I am hoping for a little help here please. I was hoping to use MOVES to access non-road inventory. For example, in 2015, what is an estimate of the age, type and model of various non-road machines like tractors, forklifts, dump trucks, etc. Alternatively, if the model produces scrappage/survival curves by machine form, that would be equally useful to me. 

Reading the readme/FAQ, I couldn't find any info on this. If there is documentation on how to extract data in this manner, I'd really appreciate it.
Thank you for your time,
Devin

**Comment by AnAbominableSnowman** [comment]
I have discovered the .POP files in the output data bases. That provides the median life in hours. There should now be a scrappage curve right. Somehow it converts an hours threshold, into a yearly attrition rate? You must make the assumption that XYZ machine form works xx hours per year?

**Comment by AnAbominableSnowman** [comment]
NATION.GRW appears to have the scrappage curves as a function of % of life consumed, and the output is % scrapped.

**Comment by AnAbominableSnowman** [comment]
And Activity.DAT records how many hours you think a machine should be a used a year. It doesn't seem to include AgeAdj though? Was that implmeneted? Can it be accessed anywhere?

**Comment by AnAbominableSnowman** [comment]
Looks like this age adjustment is not implemented? https://github.com/USEPA/EPA_MOVES_Model/blob/183eaa196b0af41f71689bf49959b4f1f5d60b11/NONROAD/NR08a/SOURCE/modyr.f#L146-L163

**Comment by mbeardsl** [comment]
Abominable-- Rather than trying to get what you want from the nonroad inputs and reports, you may want to try running MOVES-Nonroad for the desired calendar year with output by SCC and model year and then looking at the reported activity (equipment populations and hours).   

However, this could be a very large file.  To try to keep the output manageable, I'd suggest focusing on one pollutant (like NOx or CO) , one equipment sector at a time; running for a single year, month and day type; and picking a single desired county on the "geographic bounds."

**Comment by AnAbominableSnowman** [comment]
Sorry, I should have clarified, I was looking in the NONROAD section! The only open question I have is if you ever implemented an usage adjustment based on age? Older machines are used less each year. The ACTIVITY.DAT files seems to reference a "Identifier for age adjustment curve (DEFAULT=no adjustment)." But searching the repo, it looks like this was never implemented? 
Thank you!!

**Comment by mbeardsl** [comment]
The nonroad documentation ([Median Life, Annual Activity, and Load Factor Values for Nonroad engine Emissions Modeling](http://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=P10081RV.pdf)) says:

_It should be noted that the activity estimates in the NONROAD model do not currently
take into account the effect of equipment age on activity. EPA has encountered some general
information indicating that equipment activity declines as the equipment gets older. For
example, older pieces of agricultural or construction equipment might be kept as spares to be
used if newer equipment breaks down or if another piece of equipment is needed to complete a
task once in awhile. Unfortunately, EPA has been unable to obtain precise quantifiable data to
model this relationship for any type of nonroad equipment._

**Comment by AnAbominableSnowman** [comment]
Interesting. I have read through most of NR-00X files and they were very helpful. There isn't a citation, link or reference for that snippet. Do you know where the info "EPA has encountered some general information indicating that equipment activity declines as the equipment gets older" comes from? I would love to read a bit more about it.

**Comment by AnAbominableSnowman** [comment]
Thank you for your help.
