### ISSUE TITLE
Preaggregation Time Options not available

### ISSUE THREAD

**Issue by Acorn117** [USEPA/EPA_MOVES_Model#61]
I'm running a default scale inventory and can't select Time Aggregation options under Preaggregation Options in Advanced Features in MOVES4 as you could in MOVES3.  The Time Aggregation is greyed out and I can't select year, month, or day.  The default is set for an hour. Is this an intentional change in MOVES4 or a bug?  I'm hoping for a simpler, faster model run.  Thanks! Josh

**Comment by danielbizercox** [comment]
Does your RunSpec have any evaporative processes selected (such as Evap Permeation)? If so, MOVES cannot preaggregate those calculations and therefore requires Hour to be selected on the Advanced Features Panel. This is consistent with MOVES3 behavior.

To speed up these runs, you could do all processes other than the evaporative processes (such as running & starts) in one run with preagg selected, and then do the evap processes in a second run without preagg.

**Comment by Acorn117** [comment]
I don't think I selected any evaporative processes. I will need to double-check when my current model run is complete.  Thanks!

**Comment by Acorn117** [comment]
Okay, it turns out evaporative processes were selected. I turned them off and was able to preaggregate.  Thanks for your help danielbizercox!

Josh
