### ISSUE TITLE
Installer Error: Service MariaDB10_11 failed to start. Verify that you have sufficient privileges to start system services

### ISSUE THREAD

**Issue by gerrybott** [USEPA/EPA_MOVES_Model#66]
When installing Moves4.0:
The installer will ask you to set a password for Maria DB. It will seem like it set, but it does not save the password.
Upon trying to finish the install of Moves4.0, the following error message appears:
![image](https://github.com/USEPA/EPA_MOVES_Model/assets/108551664/ce7e7735-208a-4d79-b1a4-6d7b219ee5d3)

*Keep the installer open during the next steps*

Exploring the "Services" application in Windows. The service for MariaDB10_11 can be found. If you try to manually start the service, an error will appear and not allow it. This is what lead me to think the password was the problem:
![image](https://github.com/USEPA/EPA_MOVES_Model/assets/108551664/6d6f0829-1f84-4c14-bb8f-46c06b28e22b)
Right click on this process and select "properties". Change the "Password" and "Confirm password" fields to the password you set during the Moves4.0 installation. Once it has been set, click "Apply" and "Ok".
![image](https://github.com/USEPA/EPA_MOVES_Model/assets/108551664/2969ccc7-3f03-450b-b2ed-bbcebe7f6909)

Once the password has been set in the "Services" application, you can go back to the Moves4.0 installer and click "Retry"
The installer should now complete successfully:
![image](https://github.com/USEPA/EPA_MOVES_Model/assets/108551664/7b15c8c9-4e8b-493d-b6b2-e18a6670cdc1)

I do not know what causes this error, nor how to fix it in the actual installer. It seems like the installer is unable to set/save a password in the Services application in Windows. This is just a work around that we found while trying to get Moves4.0 installed. I hope this saves someone else some troubleshooting!

**Comment by danielbizercox** [comment]
Thank you for posting your steps to solve this problem. As far as we can tell, it appears to be an issue with the MariaDB installer. We're not sure what triggers it at this point, but it is very helpful to have a workaround so clearly laid out, so thanks!
