### ISSUE TITLE
Test Runspecs

### ISSUE THREAD

**Issue by HansalShah007** [USEPA/EPA_MOVES_Model#78]
Are there any default/ test runspec files that I can run directly once I install MOVES to make sure everything is working correctly?

**Comment by danielbizercox** [comment]
If you run the MOVES installer, it will run the following RunSpec: [MOVEStest.mrs.gz](https://github.com/user-attachments/files/16662556/MOVEStest.mrs.gz)

After the run, the installer checks to ensure that:
* `SELECT COUNT(*) AS errors FROM movestest.moveserror;` results in 0 rows
* `SELECT COUNT(*) AS output FROM movestest.movesoutput;` results in >0 rows

Both tests are required to pass in order for the MOVES installer to report a successful installation.

If you install with the MOVES installer and receive the successful installation message, you can be confident that your installation and configuration was successful. If you are installing MOVES manually (e.g., by cloning from this repository), you can perform the same test manually to ensure a successful installation.
